### ISSUE TITLE
UnboundLocalError: local variable 'query_hit_id' referenced before assignment

### ISSUE THREAD

**Issue by CongLiu37** [GDKO/AvP#1]
Hello, I am writing to report an error.
```
avp prepare -a ACAB.blast_ai.out -o . -f ACAB_host_genome.faa -b ACAB.blast -x group.yaml -c config.yaml
[+] Setting up
[!] Selected 1072 HGT candidates
[+] Parsing Blast file and grouping similar queries
Traceback (most recent call last):
  File "/home/c/c-liu/miniconda3/envs/avp/AvP/avp", line 6, in <module>
    main()
  File "/home/c/c-liu/miniconda3/envs/avp/AvP/depot/interface.py", line 29, in main
    prepare.main()
  File "/home/c/c-liu/miniconda3/envs/avp/AvP/depot/prepare.py", line 171, in main
    if "@" in query_hit_id:
UnboundLocalError: local variable 'query_hit_id' referenced before assignment
```

Sincerely,

Cong

**Comment by GDKO** [comment]
Hi Cong,

I have fixed the issue. Please re-download.

Cheers,
Georgios
