### ISSUE TITLE
`avp evaluate` runs forever with no progress

### ISSUE THREAD

**Issue by bheimbu** [GDKO/AvP#19]
Hi @GDKO,

really nice work you did. However, as soon as I run `avp evaluate` the program runs forever, seemingly without any progress nor end. I try to find HGT events for 845 proteins using Oribatida as EGP and Metazoa as Ingroup.

I have also two questions: 

1. What does the abbreviation EGP stand for?

2. Actually, I want to know whether proteins/genes have been acquired from fungi and/or bacteria. Which Ingroup should I use to account for this -- or is Metazoa just right?

Cheers Bastian

**Comment by GDKO** [comment]
Hi @bheimbu,

- Did ```avp detect``` finish properly? Do you get a list of candidate HGTs? ```avp evaluate``` takes some time, and you can check the progress in the ```alt_topology``` folder. Let me know if it still hangs.
- EGP stands for exclude group, setting it to ```Oribatida``` it will try to identify candidate HGTs that were introduced inside this taxonomic rank. 
- ```Metazoa`` is correct.

Cheers,
Georgios

**Comment by bheimbu** [comment]
Hi @GDKO,

`avp detect` runs without problems. I've started a new `avp evaluate` run yesterday, but it seems stuck right after the beginning. I started the run yesterday at 8:50 am and output files last changed 8:51 am. Since then, nothing happened

**Comment by GDKO** [comment]
Hi @bheimbu,

Can you send to my personal email the folder mafftgroups, the fasttree_tree_results.txt file and the config.yaml ?

Cheers,
Georgios

**Comment by bheimbu** [comment]
Hi @GDKO,

sent you an email.

Cheers Bastian

**Comment by GDKO** [comment]
Hi @bheimbu,

Apparently the character "|" in your query ids was causing the program to hung. I pushed a fix to not allow them anymore. Since this could have created some unforeseen issues, I suggest changing "|" to "_" in both your protein fasta file and the blast output (so you don't have to rerun blast) and rerun the analyses. Thanks for identifying thisproblem!

Be careful to change only the query ids and not the hit ids in the blast output.

Let me know if this fixes the issue.

Cheers,
Georgios

**Comment by bheimbu** [comment]
Hi,

I'll let you know asap. Thanks for your help.

Cheers Bastian

**Comment by bheimbu** [comment]
Hi @GDKO,

it now runs but I get following error
```
[x] 	100%
Traceback (most recent call last):
  File "/home/uni08/bheimbu/bin/AvP/oribatida/../avp", line 7, in <module>
    main()
  File "/home/uni08/bheimbu/bin/AvP/depot/interface.py", line 38, in main
    evaluate.main()
  File "/home/uni08/bheimbu/bin/AvP/depot/evaluate.py", line 204, in main
    with open(file) as f:
         ^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'alt_topology/O42814_MICMI-229747-1_scaffold132_size28375_1_g1.t1_1.fasttree.iqtree'
```
, which is true because there is no file with this name. Do I have to set `fastml: false` in the config.yaml file in order to get the iqtree files?!


Cheers Bastian

**Comment by GDKO** [comment]
Hi @bheimbu,

Can you post the output of alt_topology/O42814_MICMI-229747-1_scaffold132_size28375_1_g1.t1_1.fasttree.log ?

Cheers,
Georgios

**Comment by bheimbu** [comment]
Here you go 
[O42814_MICMI-229747-1_scaffold132_size28375_1_g1.t1_1.fasttree.log](https://github.com/GDKO/AvP/files/14883912/O42814_MICMI-229747-1_scaffold132_size28375_1_g1.t1_1.fasttree.log)

**Comment by bheimbu** [comment]
Ok, thats the problem, specified to much cores. Will change this.

My fault,

Bastian

**Comment by hydraharish123** [comment]
hey @bheimbu were you able to run avp evaluate? 
I am facing some indexing issues
Please check out #30 latest comment

**Comment by bheimbu** [comment]
Hi @hydraharish123 ,

I just needed to change the number of cores, if I remember correctly. So the number of cores must be the same in the `config.yaml` and your job script (we use a Slurm job scheduler).

Hope that helps,

Bastian
