### ISSUE TITLE
acc2taxid.py with uniref50 - ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by alexvasilikop** [GDKO/AvP#3]
Hello,

I am trying to create the tax ID file using the acc2taxid.py script and uniref50. I run:
$ python3 AvP/aux_scripts/acc2taxid.py -m uniref -i uniref50/uniref50.fasta.gz > Adineta_ricciae/sp.taxids

and get:
Traceback (most recent call last):
  File "AvP/aux_scripts/acc2taxid.py", line 50, in <module>
    main()
  File "AvP/aux_scripts/acc2taxid.py", line 43, in main
    tr, id = record.name.split("|")
ValueError: not enough values to unpack (expected 2, got 1)

When using the swissprot mode the script terminates normally.
$ python3 AvP/aux_scripts/acc2taxid.py -m swissprot -i swissprot/uniprot_sprot.fasta.gz > sp.taxids
$

Best

**Comment by alexvasilikop** [comment]
Problem was caused because the headers were not renamed as suggested in the wiki documentation. Therefore I close this issue.
